### ISSUE TITLE
Examples should include templateUrl w/ HTML loader config

### ISSUE THREAD

**Issue by tommck** [frederikprijck/angularjs-webpack-starter#1]
All the example code in here uses hard-coded HTML templates.
It would be really nice if you had the html-loader configured and used templateUrl syntax in at least one example to show how to do that.

**Comment by frederikprijck** [comment]
I've added an example: https://github.com/frederikprijck/angularjs-webpack-starter/blob/master/src/app/contacts/components/add-contact-form/add-contact-form.component.ts#L29
