### ISSUE TITLE
Problems in *.spec.ts files with jest/mocha functions.

### ISSUE THREAD

**Issue by dkokic** [frederikprijck/angularjs-webpack-starter#123]
I wonder if there is a way to resolve the problems shown by vscode in *.spec.ts files. I have tried with installing the `@types/jest` and `@types/mocha` as dev dependencies, but without success.

```
Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.ts(2582)
```

**Comment by frederikprijck** [comment]
I am not sure, this repo is using karma/jasmine.
