### ISSUE TITLE
title not working in dev server

### ISSUE THREAD

**Issue by tommck** [frederikprijck/angularjs-webpack-starter#2]
This code is not rendering properly.  The title of the window is the literal string "<%= htmlWebpackPlugin.options.title %>"

```html
   <title><%= htmlWebpackPlugin.options.title %></title>
```

**Comment by frederikprijck** [comment]
Ye I know. I still have to fix it. I will asap!

**Comment by frederikprijck** [comment]
It should be working now, can you check ?

**Comment by tommck** [comment]
Yes, that worked.. Thanks :)
