### ISSUE TITLE
Exclude AngularJS lib from bundle

### ISSUE THREAD

**Issue by artemhp** [frederikprijck/angularjs-webpack-starter#58]
Hello.
I'm going to create a single angularjs module with this starter (like ui-bootstrap-tpls-2.5.0).
Is it possible to exclude AngularJS library from the bundle on `build:prd`?

**Comment by frederikprijck** [comment]
Hey @artemhp ,

You can exclude any dependency by tweaking the webpack config, have a look at the [externals ](https://webpack.js.org/configuration/externals/)configuration option.
